language: node_js
node_js:
- '16.18.1'
env:
  global:
  - DEPLOY_REPOSITORY="git@github.com:konnectors/planeteoui.git"
  - secure: ptCOr/gRkx/GPCqmLdzQKIIe/QcBzt/Kdii8MXDcmqDTL1TqBmQWhLkfdqJEjgH+vACfsA2aH/PlJuXE8a9Fm3UvtMzHnWndagNADRfAsWi3+CSdZ/ur17E7bkE0hLjMTNLkh5hb9ZWruqVC8QLmgDYqEqGNCH7chSmlmJ9ie2UX6OdsrS6RHv4Us/nsoAGCKCuUzoI5M2ngz28wbFxeMwxFSQ6+xZ7kkIFfvn4LaE8Tm+W19H9Jmtr8DyzY2MCMLAna+msAjxVktyJmpaiFBnrjL1Ksbvinl+kzCt64HFtRHhVEf4xarHfUj+S8m9MHFdbVWIA8L6wVIQSI/FOGNjpfFa+Q7p3VqsoqkYd1fPBHygd629G6+as5qvuBfoZto0OXA1GOjxrLwfTjfSJBtJPlT3+rXTn0/IBq86keWkX5ayEGUwtgaL29wKM9Xqx3IpC7vC/qdlVjdia5VScA2kE5YaaB0pn5QUXu0sS5Pd1FQUDAYxDmKWZKTBII7xCMEB++sIb43uvl00hkrdrieGfjEzOPXUBsxEm/7yXRbKBmoyrkCuBbLave9p5ZqNhRn1q2U/ugRVvpS5B7wXNmXiDx5L7hD41bkCUNILIhacGcghxcRAGhQbtLv4WjiBKKOvBxk3+oSvmbwL30NQKb4bRIOGo8LAQisX9MWXMr/v8=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8d86ff64cc90_key -iv $encrypted_8d86ff64cc90_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
